class Movie {
+ PriceCode int
+ float64 GetCharge(days int)
+ int GetFrequentRenterPoints(days int)
}
class Rental {
+ DaysRented int
+ float64 GetCharge()
+ int GetFrequentRenterPoints()
}
class Customer {
+ string Statement()
+ string HTMLStatement()
+ float64 GetTotalCharge()
+ int GetTotalFrequentRenterPoints()
}
Customer -l-> "*" Rental
Rental -l-> "1" Movie
