class Movie {
+ PriceCode int
}
class Rental {
+ DaysRented int
+ float64 GetCharge()
+ int GetFrequentRenterPoints()
}
class Customer {
+ string Statement()
+ float64 GetTotalCharge()
+ int GetTotalFrequentRenterPoints()
}
Customer -l-> "*" Rental
Rental -l-> "1" Movie
