hide footbox
[->aCustomer: statement
activate aCustomer

aCustomer->aCustomer: GetTotalCharge()
activate aCustomer

aCustomer->aRental: *[for all rentals] GetCharge()
activate aRental
aRental->aMovie: PriceCode
deactivate aRental
deactivate aCustomer

aCustomer->aCustomer: GetTotalFrequentRenterPoints()
activate aCustomer
aCustomer->aRental: *[for all rentals] GetFrequentRenterPoints()
activate aRental
deactivate aCustomer
aRental->aMovie: PriceCode
deactivate aRental
deactivate aCustomer
